
service: assignment

frameworkVersion: '2'
plugins:
  - serverless-babel-plugin
 
custom:
  babelPresets:
    - latest
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
functions:
  currentStock:
    handler: src/handlers/get-current-stock.getCurrentStockValue
    events:
      - http:
          path: /currentStock
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                sku: true